### ISSUE TITLE
No module named 'click' docker install 

### ISSUE THREAD

**Issue by POWERFULMOVES** [Significant-Gravitas/AutoGPT-Code-Ability#295]
I installed it via docker but the app keeps exiting 

2024-06-22 01:45:48 Traceback (most recent call last):
2024-06-22 01:45:48   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-22 01:45:48   File "<frozen runpy>", line 88, in _run_code
2024-06-22 01:45:48   File "/app/codex/__main__.py", line 5, in <module>
2024-06-22 01:45:48     import click
2024-06-22 01:45:48 ModuleNotFoundError: No module named 'click'

**Comment by Drilmo** [comment]
Same for me 😭
